services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kicad_pkg_server
      POSTGRES_PASSWORD: aisler
      POSTGRES_DB: kicad_pkg_server
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: